name: Compile and Package

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sourcemod-version: [ '1.11' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache SourceMod distribution
        id: cache
        uses: actions/cache@v3
        with:
          path: sourcemod_dist
          key: sourcemod-${{ matrix.sourcemod-version }}

      - name: Download SourceMod
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir sourcemod_dist
          cd sourcemod_dist
          filename=$(curl -s https://sm.alliedmods.net/smdrop/${{ matrix.sourcemod-version }}/sourcemod-latest-linux)
          curl -O https://sm.alliedmods.net/smdrop/${{ matrix.sourcemod-version }}/$filename
          tar -xzf $filename

      - name: Compile plugin
        run: |
          chmod +x sourcemod_dist/addons/sourcemod/scripting/spcomp
          mkdir -p addons/sourcemod/plugins
          ./sourcemod_dist/addons/sourcemod/scripting/spcomp -E addons/sourcemod/scripting/stopwatch.sp -o addons/sourcemod/plugins/stopwatch.smx
          mkdir artifact
          mv addons artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: stopwatch
          path: |
            artifact/**
